apiVersion: v1
kind: Service
metadata:
  namespace: ${NAMESPACE}
  name: ${DB_SERVICE}
spec:
  selector:
    app: ${DB_APP_NAME}
  ports:
  - name: ${DB_SERVICE}
    protocol: TCP
    port: 27017
    targetPort: 27017