apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${FRONTEND_NAME}
  namespace: ${NAMESPACE}
  labels:
    role: frontend
    env: ${ENV}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: ${FRONTEND_CONTAINER}
        image: public.ecr.aws/h1l7z7k8/webapp-image:latest
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "backend:8080" # assuming backend service is on port 8080
        ports:
        - containerPort: 3000
